apiVersion: v1
kind: Service
metadata:
  name: kargo-service
spec:
  selector:
    app: kargo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Could also be ClusterIP, NodePort based on your needs
