name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: yaashwin06/kargo

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Read version from file
      id: version
      run: |
        VERSION=$(cat VERSION)
        echo "Current version: $VERSION"
        # Increment the patch version (v1.0.0 -> v1.0.1)
        VERSION_PARTS=(${VERSION//./ })
        PATCH=${VERSION_PARTS[2]}
        PATCH=$((PATCH + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo $NEW_VERSION > VERSION

    - name: Commit new version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/yaashwin/Kargo_check.git
        git add VERSION
        git commit -m "Bump version to ${{ env.VERSION }}"
        git push origin main

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ env.VERSION }} .
        docker push $IMAGE_NAME:${{ env.VERSION }}
